networks:
  symfony_microservices_net:
    driver: bridge

services:
  users:
    container_name: users
    build: users/.
    restart: on-failure
    env_file: users/.env
    environment:
      APP_NAME: users
    tty: true
    stdin_open: true
    networks:
      - symfony_microservices_net

  orders:
    container_name: orders
    build: orders/.
    restart: on-failure
    env_file: orders/.env
    environment:
      APP_NAME: orders
    tty: true
    stdin_open: true
    networks:
      - symfony_microservices_net

  notifications:
    container_name: notifications
    build: notifications/.
    restart: on-failure
    env_file: notifications/.env
    environment:
      APP_NAME: notifications
    tty: true
    stdin_open: true
    networks:
      - symfony_microservices_net

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - symfony_microservices_net

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - symfony_microservices_net
